const CharactersContext = {
  hiragana: [
    { text: 'a', pronunciation: 'あ' },
    { text: 'i', pronunciation: 'い' },
    { text: 'u', pronunciation: 'う' },
    { text: 'e', pronunciation: 'え' },
    { text: 'o', pronunciation: 'お' },
    { text: 'ka', pronunciation: 'か' },
    { text: 'ki', pronunciation: 'き' },
    { text: 'ku', pronunciation: 'く' },
    { text: 'ke', pronunciation: 'け' },
    { text: 'ko', pronunciation: 'こ' },
    { text: 'sa', pronunciation: 'さ' },
    { text: 'shi', pronunciation: 'し' },
    { text: 'su', pronunciation: 'す' },
    { text: 'se', pronunciation: 'せ' },
    { text: 'so', pronunciation: 'そ' },
    { text: 'ta', pronunciation: 'た' },
    { text: 'chi', pronunciation: 'ち' },
    { text: 'tsu', pronunciation: 'つ' },
    { text: 'te', pronunciation: 'て' },
    { text: 'to', pronunciation: 'と' },
    { text: 'na', pronunciation: 'な' },
    { text: 'ni', pronunciation: 'に' },
    { text: 'nu', pronunciation: 'ぬ' },
    { text: 'ne', pronunciation: 'ね' },
    { text: 'no', pronunciation: 'の' },
    { text: 'ha', pronunciation: 'は' },
    { text: 'hi', pronunciation: 'ひ' },
    { text: 'fu', pronunciation: 'ふ' },
    { text: 'he', pronunciation: 'へ' },
    { text: 'ho', pronunciation: 'ほ' },
    { text: 'ma', pronunciation: 'ま' },
    { text: 'mi', pronunciation: 'み' },
    { text: 'mu', pronunciation: 'む' },
    { text: 'me', pronunciation: 'め' },
    { text: 'mo', pronunciation: 'も' },
    { text: 'ya', pronunciation: 'や' },
    { text: 'yu', pronunciation: 'ゆ' },
    { text: 'yo', pronunciation: 'よ' },
    { text: 'ra', pronunciation: 'ら' },
    { text: 'ri', pronunciation: 'り' },
    { text: 'ru', pronunciation: 'る' },
    { text: 're', pronunciation: 'れ' },
    { text: 'ro', pronunciation: 'ろ' },
    { text: 'wa', pronunciation: 'わ' },
    { text: 'wo', pronunciation: 'を' },
    { text: 'n', pronunciation: 'ん' },
  ],
};

export default CharactersContext;
